# Generated by Django 3.2.4 on 2022-07-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='desc',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
